export const actionTypes={
    CHANGE_SEARCHFIELD:'CHANGE_SEARCHFIELD',
    ROBOTNAME:'ROBOTNAME',
    ROBOTID:'ROBOTID',
    REQUEST_ROBOTS_PENDING:'REQUEST_ROBOTS_PENDING',
    REQUEST_ROBOTS_SUCCESS:'REQUEST_ROBOTS_SUCCESS',
    REQUEST_ROBOTS_FAILED:'REQUEST_ROBOTS_FAILED'
};